### ISSUE TITLE
Administrative rights

### ISSUE THREAD

**Issue by SleuthKid** [SekoiaLab/Fastir_Collector#1]
Make sure the tool runs with administrative rights. Otherwise the VSS creation will lead to an exeption.

With Pyinstaller 3+ "--uac-admin" can be used for that. 
(see https://github.com/pyinstaller/pyinstaller/releases/tag/3.0)

**Comment by NoX1De** [comment]
Totally was about to post a very similar issue...there should be some sort of check coded in that warns the user that the executable has not been run with administrative rights prior to fully executing the script(s) to pull all the information.  It just runs with no warning when you do not run it with administrative rights so some users may not even realize this and when not run with administrative rights the scripts(s)/tool only dumps partial output (I believe only evtx files) and additionally the .csv is empty....just a warning to re-run with admin rights would suffice if not both that and SleuthKids suggestion as well.

**Comment by sebdraven** [comment]
It was solved with check right when FastIR is launched
