### ISSUE TITLE
JSON format

### ISSUE THREAD

**Issue by BlueBlue98** [SekoiaLab/Fastir_Collector#13]
Hi,
As far as I can see the JSON out put is not valid. I was trying to import the tools output in to Splunk and it only imported files that had only one single object. If there is  more then one object I have to manually edit the file for Splunk to accept it.
If there is more then one object for example sockets or processes, the out put is formatted as follows: 
{...}{...}{...}.

However Splunk won't import the date unless the file is formatted like this: 
[{...},{...},{...}] 
It should be a list of JSON objects as oppose to a concatenation of objects.

**Comment by davidmoneil** [comment]
Also having similar issues with the JSON output. 
Anyone know how to export as CSV?
