### ISSUE TITLE
Issue dump Windows XP

### ISSUE THREAD

**Issue by dubierthomas** [SekoiaLab/Fastir_Collector#16]
This commands  
FastIR_x86.exe --packages dump --dump sam
FastIR_x86.exe --packages dump --dump registry
FastIR_x86.exe --packages dump --dump disk

return nothing in output dir on windows (XP 32bits)

**Comment by sebdraven** [comment]
It's normal we use shadow copy to extract this information and on win xp shadowcopy is not installed by default
