### ISSUE TITLE
Issue dump ram windows10 x64 (latest version)

### ISSUE THREAD

**Issue by gugronnier** [SekoiaLab/Fastir_Collector#17]
I can't capture ram manually with "FastIR_x64.exe --packages dump --dump ram" under windows10 (last update) and admin terminal

other things like registry work fine

![capture](https://cloud.githubusercontent.com/assets/22094271/21683059/efaa60ec-d357-11e6-94fe-06e533ddc176.PNG)

**Comment by majordjuj** [comment]
Hi,

Sometimes I got the same issue with FastIR. Last time, I failed dumping the ram using FastIR_x64 on a 16gb of ram computer.

The error message isn't really explicit unfortunatly.

Thanks.

**Comment by gugronnier** [comment]
hi,

i forgot to say in the first post that my windows 10 computer has also 16GB of RAM.

maybe it is too many for FastIR_x64.

i will try on other computer with other RAM size.

**Comment by sebdraven** [comment]
Hi, we use Winpmem.sys to dump ram. When you launch, the directory is a share ?

**Comment by gugronnier** [comment]
Hi

no the directory isn't a share, i launch it directly from usb key.

**Comment by sebdraven** [comment]
I've you got the file log ?

**Comment by gugronnier** [comment]
log : i put all log i have in the first post, i don't have more information

ps : **problem solved with release V1.1 (https://github.com/SekoiaLab/Fastir_Collector/releases/tag/V1.1)**
