### ISSUE TITLE
Registry Full Listing

### ISSUE THREAD

**Issue by securitykitten** [SekoiaLab/Fastir_Collector#2]
In addition to collecting specific keys, would it be possible to give an option to write all registry contents to CSV?
Thanks!

**Comment by sebdraven** [comment]
I don't think so, but we add in few days two features: 

to have an option with the filecatcher to zip the registry files to analyse after the collect
to search a specific keys directly and record the content.

**Comment by sebdraven** [comment]
It's possible now with this option: 
[registry]
custom_registry_keys="HKCU\SOFTWARE\Locky"
registry_recursive=False

in the profile file
