### ISSUE TITLE
Issue to run the filecatcher

### ISSUE THREAD

**Issue by batidiane** [SekoiaLab/Fastir_Collector#4]
Need some help with the FIleCatcher.
When I try to run FastIR with filecatcher option, peparser could not be found. It seems that the petools is not embedded with FastIR source code.
Where can I find the petools librairy?

**Comment by sebdraven** [comment]
Have you an error with the executable file or in python directly ?

**Comment by batidiane** [comment]
I had the error when trying to execute the python code.

**Comment by sebdraven** [comment]
So, you have to install pe-tools here https://github.com/SekoiaLab/pe-tools.

**Comment by sebdraven** [comment]
have you resolved your problem ?

**Comment by SyBen** [comment]
No follow up in over a year, closing.
