### ISSUE TITLE
Issue Compiling

### ISSUE THREAD

**Issue by cryptospyder** [SekoiaLab/Fastir_Collector#5]
I've been working on "compiling" FastIR in our fork for an internal team. However, I'm running into issues that after it's compiled, it runs for a second and quits with no error code or log entries. I've installed all the dependencies and executing the python works fine and yields the results I would expect. 

Currently I'm running with no luck:

```
      pyinstaller pyinstaller.spec 
```

Any ideas?

**Comment by sebdraven** [comment]
Hi, Have you got some trace of this problem ?

**Comment by cryptospyder** [comment]
Thanks for your assistance! There's not really a trace as it seems to compile successfully. However on execution of the binary, it does nothing. Also, it should be noted that I commented out the "Rekall" sections in hook-dump.py as it was giving an error on compile. See this error below, then the full output farther below after "Rekall" had been commented out. 

> 6478 INFO: Processing hook   hook-dump.py
Traceback (most recent call last):
  File "c:\Python27\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==3.1.1', 'console_scripts', 'pyinstaller')()
  File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 755, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 701, in build
    exec(text, spec_namespace)
  File "<string>", line 31, in <module>
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 212, in __init__
    self.__postinit__()
  File "C:\Python27\lib\site-packages\PyInstaller\building\datastruct.py", line 183, in __postinit__
    self.assemble()
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 434, in assemble
    imphook_object.update_dependencies(self.graph)
  File "C:\Python27\lib\site-packages\PyInstaller\building\imphook.py", line 309, in update_dependencies
    self._process_datas(mod_graph)
  File "C:\Python27\lib\site-packages\PyInstaller\building\imphook.py", line 285, in _process_datas
    self.datas.update(set(format_binaries_and_datas(self._module.datas)))
  File "C:\Python27\lib\site-packages\PyInstaller\building\utils.py", line 426, in format_binarie

"Good" Compile


> 39 INFO: PyInstaller: 3.1.1
41 INFO: Python: 2.7.10
41 INFO: Platform: Windows-8-6.2.9200
78 INFO: UPX is available.
141 INFO: Extending PYTHONPATH with paths
['C:\\tools\\test\\Fastir_Collector']
143 INFO: checking Analysis
143 INFO: Building Analysis because out00-Analysis.toc is non existent
144 INFO: Initializing module dependency graph...
147 INFO: Initializing module graph hooks...
150 INFO: Analyzing hidden import 'dump.windows10Dump'
2486 INFO: Processing pre-safe import module hook   win32com
2907 INFO: Processing pre-find module path hook   distutils
3342 INFO: Analyzing hidden import 'dump.windows2003ServerDump'
3342 INFO: Analyzing hidden import 'dump.windows2003ServerR2Dump'
3345 INFO: Analyzing hidden import 'dump.windows2008ServerDump'
3345 INFO: Analyzing hidden import 'dump.windows2008ServerR2Dump'
3348 INFO: Analyzing hidden import 'dump.windows2012ServerDump'
3350 INFO: Analyzing hidden import 'dump.windows2012ServerR2Dump'
3351 INFO: Analyzing hidden import 'dump.windows7Dump'
3354 INFO: Analyzing hidden import 'dump.windows8Dump'
3355 INFO: Analyzing hidden import 'dump.windows8_1Dump'
3358 INFO: Analyzing hidden import 'dump.windowsVistaDump'
3360 INFO: Analyzing hidden import 'dump.windowsXPDump'
3361 INFO: Analyzing hidden import 'evt.windows10Evt'
3385 INFO: Analyzing hidden import 'evt.windows2003ServerEvt'
3388 INFO: Analyzing hidden import 'evt.windows2003ServerR2Evt'
3390 INFO: Analyzing hidden import 'evt.windows2008R2ServerEvt'
3391 INFO: Analyzing hidden import 'evt.windows2008ServerEvt'
3393 INFO: Analyzing hidden import 'evt.windows2012ServerEvt'
3394 INFO: Analyzing hidden import 'evt.windows2012ServerR2Evt'
3395 INFO: Analyzing hidden import 'evt.windows7Evt'
3398 INFO: Analyzing hidden import 'evt.windows8Evt'
3400 INFO: Analyzing hidden import 'evt.windows8_1Evt'
3404 INFO: Analyzing hidden import 'evt.windowsVistaEvt'
3407 INFO: Analyzing hidden import 'evt.windowsXPEvt'
3407 INFO: Analyzing hidden import 'filecatcher.windows10Files'
3884 INFO: Analyzing hidden import 'filecatcher.windows2003ServerFiles'
3887 INFO: Analyzing hidden import 'filecatcher.windows2003ServerR2Files'
3888 INFO: Analyzing hidden import 'filecatcher.windows2008ServerFiles'
3891 INFO: Analyzing hidden import 'filecatcher.windows2008ServerR2Files'
3894 INFO: Analyzing hidden import 'filecatcher.windows2012ServerFiles'
3895 INFO: Analyzing hidden import 'filecatcher.windows2012ServerR2Files'
3898 INFO: Analyzing hidden import 'filecatcher.windows7Files'
3901 INFO: Analyzing hidden import 'filecatcher.windows8Files'
3904 INFO: Analyzing hidden import 'filecatcher.windows8_1Files'
3907 INFO: Analyzing hidden import 'filecatcher.windowsVistaFiles'
3910 INFO: Analyzing hidden import 'filecatcher.windowsXPFiles'
3911 INFO: Analyzing hidden import 'fs.windows10Files'
4069 INFO: Analyzing hidden import 'fs.windows2003ServerFiles'
4072 INFO: Analyzing hidden import 'fs.windows2003ServerR2Files'
4075 INFO: Analyzing hidden import 'fs.windows2008ServerFiles'
4077 INFO: Analyzing hidden import 'fs.windows2008ServerR2Files'
4079 INFO: Analyzing hidden import 'fs.windows2012ServerFiles'
4082 INFO: Analyzing hidden import 'fs.windows2012ServerR2Files'
4087 INFO: Analyzing hidden import 'fs.windows7Files'
4091 INFO: Analyzing hidden import 'fs.windows8Files'
4095 INFO: Analyzing hidden import 'fs.windows8_1Files'
4098 INFO: Analyzing hidden import 'fs.windowsVistaFiles'
4101 INFO: Analyzing hidden import 'fs.windowsXPFiles'
4102 INFO: Analyzing hidden import 'health.windows10StateMachine'
5138 INFO: Processing pre-safe import module hook   _xmlplus
5690 INFO: Analyzing hidden import 'health.windows2003ServerR2StateMachine'
5696 INFO: Analyzing hidden import 'health.windows2003ServerStateMachine'
5702 INFO: Analyzing hidden import 'health.windows2008ServerR2StateMachine'
5706 INFO: Analyzing hidden import 'health.windows2008ServerStateMachine'
5710 INFO: Analyzing hidden import 'health.windows2012ServerR2StateMachine'
5713 INFO: Analyzing hidden import 'health.windows2012ServerStateMachine'
5717 INFO: Analyzing hidden import 'health.windows7StateMachine'
5722 INFO: Analyzing hidden import 'health.windows8StateMachine'
5725 INFO: Analyzing hidden import 'health.windows8_1StateMachine'
5729 INFO: Analyzing hidden import 'health.windowsVistaStateMachine'
5732 INFO: Analyzing hidden import 'health.windowsXPStateMachine'
5740 INFO: Analyzing hidden import 'memory.windows10Memory'
6039 INFO: Analyzing hidden import 'memory.windows2003ServerMemory'
6042 INFO: Analyzing hidden import 'memory.windows2003ServerR2Memory'
6043 INFO: Analyzing hidden import 'memory.windows2008ServerMemory'
6046 INFO: Analyzing hidden import 'memory.windows2008ServerR2Memory'
6048 INFO: Analyzing hidden import 'memory.windows2012Memory'
6049 INFO: Analyzing hidden import 'memory.windows2012ServerMemory'
6052 INFO: Analyzing hidden import 'memory.windows2012ServerR2Memory'
6054 INFO: Analyzing hidden import 'memory.windows7Memory'
6059 INFO: Analyzing hidden import 'memory.windows8Memory'
6062 INFO: Analyzing hidden import 'memory.windows8_1Memory'
6064 INFO: Analyzing hidden import 'memory.windowsVistaMemory'
6065 INFO: Analyzing hidden import 'memory.windowsXPMemory'
6068 INFO: Analyzing hidden import 'registry.windows10Users'
6095 INFO: Analyzing hidden import 'registry.windows2003ServerR2Users'
6098 INFO: Analyzing hidden import 'registry.windows2003ServerUsers'
6101 INFO: Analyzing hidden import 'registry.windows2008ServerR2Users'
6102 INFO: Analyzing hidden import 'registry.windows2008ServerUsers'
6105 INFO: Analyzing hidden import 'registry.windows2012ServerR2Users'
6108 INFO: Analyzing hidden import 'registry.windows2012ServerUsers'
6110 INFO: Analyzing hidden import 'registry.windows2012Users'
6111 INFO: Analyzing hidden import 'registry.windows7Users'
6112 INFO: Analyzing hidden import 'registry.windows8Users'
6115 INFO: Analyzing hidden import 'registry.windows8_1Users'
6117 INFO: Analyzing hidden import 'registry.windowsVistaUsers'
6118 INFO: Analyzing hidden import 'registry.windowsXPUsers'
6121 INFO: running Analysis out00-Analysis.toc
6124 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
  required by C:\Python27\python.exe
6213 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_3da38fdebd0e6822.manifest
6216 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_acd0e4ffe1daef0a.manifest
6220 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_acd388d7e1d8689f.manifest
6226 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9177_none_acd40623e1d81331.manifest
6314 INFO: Searching for assembly amd64_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.30729.9177_none ...
6315 INFO: Found manifest C:\WINDOWS\WinSxS\Manifests\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9177_none_08e695a3a83b6ce3.manifest
6319 INFO: Searching for file msvcr90.dll
6319 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9177_none_08e695a3a83b6ce3\msvcr90.dll
6322 INFO: Searching for file msvcp90.dll
6322 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9177_none_08e695a3a83b6ce3\msvcp90.dll
6324 INFO: Searching for file msvcm90.dll
6325 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9177_none_08e695a3a83b6ce3\msvcm90.dll
6411 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_3da38fdebd0e6822.manifest
6414 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_acd0e4ffe1daef0a.manifest
6417 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_acd388d7e1d8689f.manifest
6421 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9177_none_acd40623e1d81331.manifest
6424 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9177)
6480 INFO: Analyzing main.py
6577 INFO: Looking for import hooks ...
6582 INFO: Processing hook   hook-distutils.py
6582 INFO: Processing hook   hook-sysconfig.py
6585 INFO: Processing hook   hook-xml.py
6661 INFO: Processing hook   hook-httplib.py
6663 INFO: Processing hook   hook-dump.py
6664 INFO: Processing hook   hook-_tkinter.py
6753 INFO: checking Tree
6753 INFO: Building Tree because out00-Tree.toc is non existent
6755 INFO: Building Tree out00-Tree.toc
6921 INFO: checking Tree
6923 INFO: Building Tree because out01-Tree.toc is non existent
6924 INFO: Building Tree out01-Tree.toc
6946 INFO: Processing hook   hook-distorm3.py
6949 INFO: Processing hook   hook-distorm3.py
6950 INFO: Processing hook   hook-pywintypes.py
7016 INFO: Processing hook   hook-encodings.py
7360 INFO: Processing hook   hook-sqlite3.py
7365 INFO: Processing hook   hook-win32com.py
7433 INFO: Processing hook   hook-pythoncom.py
7523 INFO: Looking for ctypes DLLs
7531 WARNING: library checksignfromcat.dll required via ctypes not found
7541 WARNING: library checksignfromcat.dll required via ctypes not found
7569 INFO: Analyzing run-time hooks ...
7578 INFO: Including run-time hook 'pyi_rth__tkinter.py'
7579 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
7597 INFO: Looking for dynamic libraries
7975 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.4148_none_a551ff35e6a96bed.manifest
7979 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_a554a30de6a6e582.manifest
8068 INFO: Searching for assembly amd64_Microsoft.VC90.MFC_1fc8b3b9a1e18e3b_9.0.30729.6161_none ...
8069 INFO: Found manifest C:\WINDOWS\WinSxS\Manifests\amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_044aad0bab1eb146.manifest
8072 INFO: Searching for file mfc90.dll
8072 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_044aad0bab1eb146\mfc90.dll
8075 INFO: Searching for file mfc90u.dll
8075 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_044aad0bab1eb146\mfc90u.dll
8078 INFO: Searching for file mfcm90.dll
8079 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_044aad0bab1eb146\mfcm90.dll
8082 INFO: Searching for file mfcm90u.dll
8082 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_044aad0bab1eb146\mfcm90u.dll
8173 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.4148_none_a551ff35e6a96bed.manifest
8176 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_a554a30de6a6e582.manifest
8179 INFO: Adding redirect Microsoft.VC90.MFC version (9, 0, 21022, 8) -> (9, 0, 30729, 6161)
8434 INFO: Looking for eggs
8437 INFO: Using Python library C:\WINDOWS\system32\python27.dll
8437 INFO: Found binding redirects:
[BindingRedirect(name=u'Microsoft.VC90.MFC', language=None, arch=u'amd64', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 6161), publicKeyToken=u'1fc8b3b9a1e18e3b'), BindingRedirect(name=u'Microsoft.VC90.CRT', language=None, arch=u'amd64', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 9177), publicKeyToken=u'1fc8b3b9a1e18e3b')]
8459 INFO: Warnings written to C:\tools\test\Fastir_Collector-test\build\pyinstaller\warnpyinstaller.txt
8713 INFO: checking PYZ
8713 INFO: Building PYZ because out00-PYZ.toc is non existent
8716 INFO: Building PYZ (ZlibArchive) C:\tools\test\Fastir_Collector-test\build\pyinstaller\out00-PYZ.pyz
9262 INFO: checking Tree
9262 INFO: Building Tree because out02-Tree.toc is non existent
9263 INFO: Building Tree out02-Tree.toc
9268 INFO: checking Tree
9268 INFO: Building Tree because out03-Tree.toc is non existent
9269 INFO: Building Tree out03-Tree.toc
9275 INFO: checking Tree
9275 INFO: Building Tree because out04-Tree.toc is non existent
9276 INFO: Building Tree out04-Tree.toc
9282 INFO: checking Tree
9282 INFO: Building Tree because out05-Tree.toc is non existent
9282 INFO: Building Tree out05-Tree.toc
9291 INFO: checking Tree
9291 INFO: Building Tree because out06-Tree.toc is non existent
9292 INFO: Building Tree out06-Tree.toc
9299 INFO: checking Tree
9299 INFO: Building Tree because out07-Tree.toc is non existent
9301 INFO: Building Tree out07-Tree.toc
9305 INFO: checking Tree
9306 INFO: Building Tree because out08-Tree.toc is non existent
9309 INFO: Building Tree out08-Tree.toc
9315 INFO: checking Tree
9316 INFO: Building Tree because out09-Tree.toc is non existent
9318 INFO: Building Tree out09-Tree.toc
9325 INFO: checking Tree
9325 INFO: Building Tree because out10-Tree.toc is non existent
9327 INFO: Building Tree out10-Tree.toc
9334 INFO: checking Tree
9334 INFO: Building Tree because out11-Tree.toc is non existent
9335 INFO: Building Tree out11-Tree.toc
9339 INFO: checking Tree
9341 INFO: Building Tree because out12-Tree.toc is non existent
9342 INFO: Building Tree out12-Tree.toc
9347 INFO: checking Tree
9347 INFO: Building Tree because out13-Tree.toc is non existent
9348 INFO: Building Tree out13-Tree.toc
9360 INFO: checking PKG
9360 INFO: Building PKG because out00-PKG.toc is non existent
9361 INFO: Building PKG (CArchive) out00-PKG.pkg
9483 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9177)
11564 INFO: Bootloader C:\Python27\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
26108 INFO: checking EXE
26110 INFO: Building EXE because out00-EXE.toc is non existent
26111 INFO: Building EXE from out00-EXE.toc
26160 INFO: SRCPATH [('sekoia.ico', None)]
26161 INFO: Updating icons from ['sekoia.ico'] to c:\users\dkaminsky\appdata\local\temp\tmpamy9kx
26163 INFO: Writing RT_GROUP_ICON 0 resource with 20 bytes
26164 INFO: Writing RT_ICON 1 resource with 16936 bytes
26210 INFO: Executing - upx --lzma -q C:\Users\dkaminsky\AppData\Roaming\pyinstaller\bincache01_py27_64bit\tmpamy9kx
26348 INFO: Appending archive to EXE C:\tools\test\Fastir_Collector-test\dist\FastIR_x64.exe

**Comment by sebdraven** [comment]
Ok so it should be fine. When you execute FastIR_x64.exe, have you got traces ?

**Comment by cryptospyder** [comment]
![capture](https://cloud.githubusercontent.com/assets/8184737/16137947/8cdbefee-3406-11e6-8a60-6ea85e4e302f.JPG)

The above picture is what I get when I try to execute. It runs but no data is collected. In the mater branch I have changed the name of fastir.conf.sample to fastir.conf so that the pyinstaller.spec file will work. 

I am currently compiling on Windows 10 with: 

> pyinstaller pyinstaller.spec

**Comment by sebdraven** [comment]
oKi Have you got a FastIR.log in the folder where FastIR was executed ? If yes, can you copy it here please ?

**Comment by cryptospyder** [comment]
It creates a log but the log is empty.

**Comment by thansau239** [comment]
I have issue
Traceback (most recent call last):
  File "main.py", line 20, in <module>
  File "c:\python27\lib\site-packages\PyInstaller-3.3.dev0+483c819-py2.7.egg\PyI
nstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "factory\factory.py", line 3, in <module>
ImportError: No module named settings
Failed to execute script main

**Comment by SyBen** [comment]
Should be fixed in 1.1, module detection was different in pyinstaller.
